version: '3.8'

services:
    mysql:
        image: mysql:latest
        container_name: plant_mysql
        environment:
            MYSQL_DATABASE: plant_mysql
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3333:3306"
        volumes:
            - ./data/conf.d:/etc/mysql/conf.d
            - ./data/logs:/logs
            - ./data/mysql:/var/lib/mysql
        networks:
            - plant_network

networks:
    plant_network:
        driver: bridge
